# Generated by Django 6.0.7 on 2026-08-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_schooladmininvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmininvitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
