# Generated by Django 6.0.7 on 2026-08-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_schooladmininvitation_revoked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmininvitation',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher')], default='ADMIN', max_length=10),
        ),
    ]
