# Generated by Django 6.0.7 on 2026-08-11 04:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_accuracy_m', models.PositiveIntegerField()),
                ('distance_m', models.FloatField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('OUT_OF_RANGE', 'Out of range'), ('NEEDS_REVIEW', 'Needs review')], max_length=20)),
                ('reason', models.TextField()),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='schools.geofence')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
